version: "3.7"
services:
  init-env:
    image: ntdtfr/env-initializer
    configs:
      - source: config-env
        target: /tmp/env.conf
    deploy:
      mode: replicated
      replicas: 1
configs:
  config-env:
    file: ./config/test.conf
