version: "3.7"
services:
  env-init:
    image: ntdtfr/env-initializer
    configs:
      - source: env.conf
        target: /opt/conf/env.conf
    deploy:
      mode: replicated
      replicas: 1
configs:
  env.conf:
    file: ./config/test.env
